import React from "react"
import { getLoginInfo } from "../utils/LoginInfo"

const ReportsHeader =({startingDate,endingDate})=>{

    const Mydate = new Date().toLocaleString();
    return(
        <>
        <div className="max-w-7xl">
               
                <h1 className='text-center  text-blue-600 rounded text-lg font-bold'>GOVERNMENT OF NCT DELHI</h1>
                <h3 className='text-center  text-blue-600 rounded text-sm font-bold'>DELHI SACHIVALAYA</h3>
                    <div className='text-center'>
                    <p className='inline text-md font-bold text-blue-600 ml-8'>Generated on: <span>{Mydate}</span></p>
                    </div>
                    <p className='text-center'>
                  <span className='ml-6 font-bold text-blue-600'>Report From: {startingDate} </span>
                    <span className='ml-6 font-bold text-blue-600'>Report To: {endingDate}</span> 
                    <span className='ml-6 font-bold text-blue-600'>Report Generated By:  {getLoginInfo()?.userName}</span></p>
         </div>
        </>
    )
}
export default ReportsHeader;